version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Building SAM Application"
      - sam build
      - sam package \
          --output-template-file packaged.yaml \
          --s3-bucket myapp-sam-artifact-bucket
artifacts:
  files:
    - packaged.yaml
